getPost:
  path: post/{id}
  controller: App\Controller\PostsController:postAction

getPosts:
  path: posts
  controller: App\Controller\PostsController:postsAction

addPost:
  path: posts
  controller: App\Controller\PostsController:createPost

